package fatec.poo.view;

import fatec.poo.control.DaoHospede;
import fatec.poo.control.DaoQuarto;
import fatec.poo.control.DaoRecepcionista;
import fatec.poo.control.DaoRegistro;
import fatec.poo.control.PreparaConexao;
import fatec.poo.model.Hospede;
import fatec.poo.model.Quarto;
import fatec.poo.model.Recepcionista;
import fatec.poo.model.Registro;
import java.sql.Connection;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author eros
 */
public class GuiRegistro extends javax.swing.JFrame {

    /**
     * Creates new form GuiRegistro
     */
    public GuiRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtRegFunc = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtCpfHospede = new javax.swing.JFormattedTextField();
        txtNumQuarto = new javax.swing.JTextField();
        txtDtEntrada = new javax.swing.JFormattedTextField();
        txtDtSaida = new javax.swing.JFormattedTextField();
        txtValHospedagem = new javax.swing.JTextField();
        btnReservar = new javax.swing.JButton();
        btnLiberar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnConsultaCodigo = new javax.swing.JButton();
        btnConsultaFunc = new javax.swing.JButton();
        lblNomeFunc = new javax.swing.JLabel();
        btnConsultaHospede = new javax.swing.JButton();
        lblNomeHospede = new javax.swing.JLabel();
        btnConsultaSituacao = new javax.swing.JButton();
        lblSituacao = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Hospedagem");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("Registro Funcional");

        jLabel3.setText("CPF Hóspede");

        jLabel5.setText("Data saída");

        jLabel6.setText("Valor Hospedagem");

        jLabel7.setText("Nº. Quarto");

        jLabel8.setText("Data entrada");

        txtRegFunc.setEnabled(false);

        try {
            txtCpfHospede.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfHospede.setEnabled(false);

        txtNumQuarto.setEnabled(false);

        try {
            txtDtEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDtEntrada.setEnabled(false);

        try {
            txtDtSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDtSaida.setEnabled(false);

        txtValHospedagem.setEnabled(false);

        btnReservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnReservar.setText("Reservar");
        btnReservar.setEnabled(false);
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnLiberar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/rem.png"))); // NOI18N
        btnLiberar.setText("Liberar");
        btnLiberar.setEnabled(false);
        btnLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnConsultaCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultaCodigo.setText("Consultar");
        btnConsultaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaCodigoActionPerformed(evt);
            }
        });

        btnConsultaFunc.setText("...");
        btnConsultaFunc.setEnabled(false);
        btnConsultaFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaFuncActionPerformed(evt);
            }
        });

        lblNomeFunc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblNomeFunc.setEnabled(false);

        btnConsultaHospede.setText("...");
        btnConsultaHospede.setEnabled(false);
        btnConsultaHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaHospedeActionPerformed(evt);
            }
        });

        lblNomeHospede.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblNomeHospede.setEnabled(false);

        btnConsultaSituacao.setText("...");
        btnConsultaSituacao.setEnabled(false);
        btnConsultaSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaSituacaoActionPerformed(evt);
            }
        });

        lblSituacao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblSituacao.setEnabled(false);

        jLabel4.setText("Situação");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReservar)
                        .addGap(10, 10, 10)
                        .addComponent(btnLiberar)
                        .addGap(10, 10, 10)
                        .addComponent(btnSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRegFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCpfHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtValHospedagem, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDtSaida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addComponent(txtDtEntrada, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConsultaHospede)
                                .addGap(18, 18, 18)
                                .addComponent(lblNomeHospede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(btnConsultaSituacao)
                                .addGap(18, 18, 18)
                                .addComponent(lblSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnConsultaCodigo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConsultaFunc)
                                .addGap(18, 18, 18)
                                .addComponent(lblNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultaCodigo))))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtRegFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConsultaFunc)
                    .addComponent(lblNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnConsultaHospede)
                            .addComponent(lblNomeHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtCpfHospede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConsultaSituacao)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDtSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValHospedagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReservar)
                    .addComponent(btnLiberar)
                    .addComponent(btnSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        prepCon = new PreparaConexao("LTS","lutiemi");
        prepCon.setDriver("oracle.jdbc.driver.OracleDriver");
        prepCon.setConnectionString("jdbc:oracle:thin:@127.0.0.1:1521/XEPDB1");
        
        conn = prepCon.abrirConexao();
        daoRegistro = new DaoRegistro(conn);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        prepCon.fecharConexao();
    }//GEN-LAST:event_formWindowClosed

    private void btnConsultaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaCodigoActionPerformed
        try {
            int codigo = Integer.parseInt(txtCodigo.getText());
            registro = null;
            registro = daoRegistro.consultar(codigo);

            if (registro == null) {
                txtCodigo.setEnabled(false);
                btnConsultaFunc.setEnabled(true);
                txtRegFunc.setEnabled(true);
                btnConsultaCodigo.setEnabled(false);
                
                txtRegFunc.requestFocus();
            } else {
                txtRegFunc.setText(String.valueOf(registro.getRecepcionista().getRegFunc()));
                lblNomeFunc.setText(registro.getRecepcionista().getNome());
                txtCpfHospede.setText(registro.getHospede().getCpf());
                lblNomeHospede.setText(registro.getHospede().getNome());
                txtNumQuarto.setText(String.valueOf(registro.getQuarto().getNumero()));
                if (registro.getQuarto().getSituacao()){
                    lblSituacao.setText("Ocupado");
                } else {
                    lblSituacao.setText("Livre");
                }
                txtCodigo.setEnabled(false);
                btnConsultaCodigo.setEnabled(false);
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                txtDtEntrada.setText(registro.getDataEntrada().format(formatter));
                if (registro.getDataSaida() != null) {
                    txtDtSaida.setText(registro.getDataSaida().format(formatter));
                    txtValHospedagem.setText(String.valueOf(registro.getValorHospedagem()));
                    
                } else {
                    txtDtSaida.setEnabled(true); 
                    txtDtSaida.requestFocus();
                    btnLiberar.setEnabled(true);
                    btnReservar.setEnabled(false);
                }
            }
        } 
        catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                "Digite um número inteiro válido para o código do registro.",
                "Entrada inválida",
                JOptionPane.WARNING_MESSAGE);
            txtCodigo.setText(null);
            txtCodigo.requestFocus();
        }
    }//GEN-LAST:event_btnConsultaCodigoActionPerformed

    private void btnConsultaFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaFuncActionPerformed
        try {
            int regFunc = Integer.parseInt(txtRegFunc.getText());
            
            recepcionista = null;
            recepcionista = new DaoRecepcionista(conn).consultar(regFunc);
            if (recepcionista == null) {
                JOptionPane.showMessageDialog(this,
                    "Recepcionista não cadastrado",
                    "Entrada inválida",
                    JOptionPane.WARNING_MESSAGE);
                txtRegFunc.requestFocus();
            } else {
                lblNomeFunc.setText(recepcionista.getNome());
                txtRegFunc.setEnabled(false);
                btnConsultaFunc.setEnabled(false);

                txtCpfHospede.setEnabled(true);
                txtCpfHospede.requestFocus();
                btnConsultaHospede.setEnabled(true);
            }
        }
        catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                "Digite um número inteiro válido para o registro do funcionário.",
                "Entrada inválida",
                JOptionPane.WARNING_MESSAGE);
            txtRegFunc.setText(null);
            txtRegFunc.requestFocus();
        }
    }//GEN-LAST:event_btnConsultaFuncActionPerformed

    private void btnConsultaHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaHospedeActionPerformed
        String cpf = txtCpfHospede.getText().replaceAll("[^\\d]", "");
        
        hospede = null;
        hospede = new DaoHospede(conn).consultar(cpf);

        if (hospede == null) {
            JOptionPane.showMessageDialog(this,
                "Hospede não cadastrado",
                "Entrada inválida",
                JOptionPane.WARNING_MESSAGE);
            txtCpfHospede.requestFocus();
        } else {
            lblNomeHospede.setText(hospede.getNome());
            txtCpfHospede.setEnabled(false);
            btnConsultaHospede.setEnabled(false);

            txtNumQuarto.setEnabled(true);
            txtNumQuarto.requestFocus();
            btnConsultaSituacao.setEnabled(true);
        }
    }//GEN-LAST:event_btnConsultaHospedeActionPerformed

    private void btnConsultaSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaSituacaoActionPerformed
        try {
            int numQuarto = Integer.parseInt(txtNumQuarto.getText());
            
            quarto = null;
            quarto = new DaoQuarto(conn).consultar(numQuarto);
            
            if (quarto == null) {
                JOptionPane.showMessageDialog(this,
                    "Quarto não cadastrado",
                    "Entrada inválida",
                    JOptionPane.WARNING_MESSAGE);
                txtNumQuarto.requestFocus();
            } else {
                if (quarto.getSituacao()){
                    lblSituacao.setText("Ocupado");
                    JOptionPane.showMessageDialog(this,
                        "Quarto ocupado",
                        "Entrada inválida",
                        JOptionPane.WARNING_MESSAGE);
                    txtNumQuarto.requestFocus();
                } else {
                    lblSituacao.setText("Livre");

                    txtDtEntrada.setEnabled(true);
                    txtDtEntrada.requestFocus();
                    btnReservar.setEnabled(true);
                }
            }
        }
        catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                "Digite um número inteiro válido para o número do quarto.",
                "Entrada inválida",
                JOptionPane.WARNING_MESSAGE);
            txtNumQuarto.setText(null);
            txtNumQuarto.requestFocus();
        }
    }//GEN-LAST:event_btnConsultaSituacaoActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate dtEntrada = LocalDate.parse(txtDtEntrada.getText(), formatter);
            
            int codigo = Integer.parseInt(txtCodigo.getText());
            registro = new Registro(codigo, dtEntrada, recepcionista);
            registro.reservarQuarto(hospede, quarto);
            
            daoRegistro.inserir(registro);              // salvando no BD

            // reiniciar GUI
            txtCodigo.setText(null);
            txtCodigo.setEnabled(true);
            txtCodigo.requestFocus();
            btnConsultaCodigo.setEnabled(true);

            txtRegFunc.setText(null);
            lblNomeFunc.setText(null);
            txtCpfHospede.setText(null);
            lblNomeHospede.setText(null);

            txtNumQuarto.setText(null);
            txtNumQuarto.setEnabled(false);
            btnConsultaSituacao.setEnabled(false);
            lblSituacao.setText(null);
            lblSituacao.setEnabled(false);

            txtDtEntrada.setText(null);
            txtDtEntrada.setEnabled(false);    
        }
        catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this,
                "Digite uma data válida.",
                "Entrada inválida",
                JOptionPane.WARNING_MESSAGE);
            txtDtEntrada.setText(null);
            txtDtEntrada.requestFocus();
        }
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate dtSaida = LocalDate.parse(txtDtSaida.getText(), formatter);
            registro.setDataSaida(dtSaida);
            
            double valorHosp = registro.liberarQuarto();
            
            daoRegistro.alterar(registro);              // salvando no BD
            
            txtValHospedagem.setText(String.valueOf(valorHosp));
            txtDtSaida.setEnabled(false);
            btnLiberar.setEnabled(false);
        }
        catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this,
                "Digite uma data válida.",
                "Entrada inválida",
                JOptionPane.WARNING_MESSAGE);
            txtDtSaida.setText(null);
            txtDtSaida.requestFocus();
        }
    }//GEN-LAST:event_btnLiberarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultaCodigo;
    private javax.swing.JButton btnConsultaFunc;
    private javax.swing.JButton btnConsultaHospede;
    private javax.swing.JButton btnConsultaSituacao;
    private javax.swing.JButton btnLiberar;
    private javax.swing.JButton btnReservar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblNomeFunc;
    private javax.swing.JLabel lblNomeHospede;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtCpfHospede;
    private javax.swing.JFormattedTextField txtDtEntrada;
    private javax.swing.JFormattedTextField txtDtSaida;
    private javax.swing.JTextField txtNumQuarto;
    private javax.swing.JTextField txtRegFunc;
    private javax.swing.JTextField txtValHospedagem;
    // End of variables declaration//GEN-END:variables

    private DaoRegistro daoRegistro;
    private Registro registro;
    private PreparaConexao prepCon;
    private Connection conn;
    
    private Recepcionista recepcionista;
    private Hospede hospede;
    private Quarto quarto;
}
